import { getReadingById, getReadings } from "@/data/brics";
import { computeRisk, levelFromScore } from "@/lib/risk";
import { callGemini, parseJsonLoose } from "@/lib/gemini.server";

export interface ImageAnalysis {
  pollution_detected: boolean;
  pollution_type: string;
  severity: "none" | "low" | "medium" | "high" | "severe" | string;
  confidence: number;
  visual_indicators: string[];
  possible_sources: string[];
  environmental_risk: string;
  recommended_action: string;
}

export interface AiEnvelope<T> {
  data: T;
  ai: {
    generated_by: "gemini" | "fallback";
    provider?: string;
    notice: string;
    error?: string;
  };
}

const FALLBACK_NOTICE =
  "Google Gemini was unavailable, so this is a deterministic DEMO/FALLBACK result produced by the local rule engine — not an AI analysis.";
const GEMINI_NOTICE =
  "AI-assisted analysis generated by Google Gemini. Not an official environmental diagnosis.";

/* ------------------------------------------------------------------ cache */
type Entry = { at: number; value: unknown };
const cache = new Map<string, Entry>();
const TTL = 10 * 60 * 1000;

async function cached<T>(key: string, fn: () => Promise<T>): Promise<T> {
  const hit = cache.get(key);
  if (hit && Date.now() - hit.at < TTL) return hit.value as T;
  const value = await fn();
  cache.set(key, { at: Date.now(), value });
  if (cache.size > 200) cache.delete(cache.keys().next().value as string);
  return value;
}

/* --------------------------------------------------------- image analysis */
const IMAGE_SYSTEM = `You are an environmental image-analysis model for BRICS AirShield, a cross-border air-pollution intelligence prototype.
Analyse the photograph for visible air-pollution evidence (smoke plumes, haze, flaring, dust, open burning, vehicle exhaust, industrial stacks).
Be conservative: if the sky looks clear or the image is unrelated, report pollution_detected=false with low severity.
Never claim to know the exact facility, company or legal violation. Reply with JSON only, matching exactly:
{"pollution_detected":boolean,"pollution_type":string,"severity":"none"|"low"|"medium"|"high"|"severe","confidence":number between 0 and 1,"visual_indicators":string[],"possible_sources":string[],"environmental_risk":string,"recommended_action":string}`;

export async function analyzeImageImpl(input: {
  mimeType: string;
  data: string;
  city?: string;
  country?: string;
  note?: string;
}): Promise<AiEnvelope<ImageAnalysis>> {
  if (!/^image\/(png|jpe?g|webp|gif)$/i.test(input.mimeType)) {
    throw new Error("Unsupported image type. Use PNG, JPEG, WEBP or GIF.");
  }
  const ctx = [
    input.city ? `Reported location: ${input.city}, ${input.country ?? ""}` : null,
    input.note ? `Reporter note: ${input.note}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const res = await callGemini({
    system: IMAGE_SYSTEM,
    prompt: `${ctx}\n\nAnalyse this image for air-pollution evidence and return the JSON object.`.trim(),
    image: { mimeType: input.mimeType, data: input.data },
    json: true,
  });

  if (res.ok) {
    const parsed = parseJsonLoose<ImageAnalysis>(res.text);
    if (parsed && typeof parsed.pollution_detected === "boolean") {
      return {
        data: {
          ...parsed,
          confidence: Math.max(0, Math.min(1, Number(parsed.confidence) || 0)),
          visual_indicators: parsed.visual_indicators ?? [],
          possible_sources: parsed.possible_sources ?? [],
        },
        ai: { generated_by: "gemini", provider: res.provider, notice: GEMINI_NOTICE },
      };
    }
  }

  return {
    data: {
      pollution_detected: false,
      pollution_type: "undetermined",
      severity: "none",
      confidence: 0,
      visual_indicators: ["Image could not be analysed by the AI model."],
      possible_sources: [],
      environmental_risk:
        "No visual assessment available. Risk is estimated from environmental sensor values only.",
      recommended_action:
        "Retry the analysis, or verify the location using ground sensor data before escalation.",
    },
    ai: {
      generated_by: "fallback",
      notice: FALLBACK_NOTICE,
      error: res.ok ? "Model reply was not valid JSON." : res.error,
    },
  };
}

/* ------------------------------------------------------------ risk detail */
export function riskContextFor(cityId: string) {
  const reading = getReadingById(cityId);
  if (!reading) return null;
  return { reading, risk: computeRisk(reading) };
}

export async function explainRiskImpl(cityId: string): Promise<AiEnvelope<{ text: string }>> {
  const ctx = riskContextFor(cityId);
  if (!ctx) throw new Error("Unknown city id");
  const { reading, risk } = ctx;

  return cached(`explain:${cityId}:${reading.timestamp}`, async () => {
    const res = await callGemini({
      system:
        "You are an air-quality analyst for BRICS AirShield. Explain risk drivers plainly in 90-130 words for a city official. Use only the supplied data. Never invent sensor readings, government sources or forecasts. State that values are prototype/demo estimates.",
      prompt: `City: ${reading.city}, ${reading.country} (${reading.region})
PM2.5 ${reading.pm25} µg/m³ | PM10 ${reading.pm10} | AQI ${reading.aqi}
Temp ${reading.temperature}°C | Humidity ${reading.humidity}% | Wind ${reading.wind_speed} m/s | Pressure ${reading.pressure} hPa
Prototype risk score: ${risk.risk_score}/100 (${risk.risk_level})
Factor contributions: ${risk.factors.map((f) => `${f.label} ${f.points}/${f.max}`).join("; ")}

Explain why this location carries this risk level and what an authority should investigate first.`,
    });

    if (res.ok) {
      return {
        data: { text: res.text.trim() },
        ai: { generated_by: "gemini" as const, provider: res.provider, notice: GEMINI_NOTICE },
      };
    }
    const top = risk.factors.slice(0, 3).map((f) => `${f.label} (${f.points}/${f.max}) — ${f.detail}`);
    return {
      data: {
        text: `${reading.city} scores ${risk.risk_score}/100 (${risk.risk_level}) on the prototype risk model. Leading contributors:\n• ${top.join("\n• ")}\nThese are simulated demo values combined by a transparent weighted model, not an official forecast.`,
      },
      ai: { generated_by: "fallback" as const, notice: FALLBACK_NOTICE, error: res.error },
    };
  });
}

/* ---------------------------------------------------------------- copilot */
function globalContext() {
  const readings = getReadings();
  const rows = readings.map((r) => {
    const risk = computeRisk(r);
    return { ...r, risk_score: risk.risk_score, risk_level: risk.risk_level };
  });
  const byCountry = new Map<string, { n: number; aqi: number; risk: number; high: number }>();
  for (const r of rows) {
    const e = byCountry.get(r.country) ?? { n: 0, aqi: 0, risk: 0, high: 0 };
    e.n++;
    e.aqi += r.aqi;
    e.risk += r.risk_score;
    if (r.risk_score >= 55) e.high++;
    byCountry.set(r.country, e);
  }
  const countryLines = [...byCountry.entries()].map(
    ([c, e]) =>
      `${c}: ${e.n} cities, avg AQI ${Math.round(e.aqi / e.n)}, avg risk ${Math.round(e.risk / e.n)}, ${e.high} high-or-worse`,
  );
  const top = [...rows].sort((a, b) => b.risk_score - a.risk_score).slice(0, 8);
  return `COUNTRY SUMMARY (simulated demo dataset)\n${countryLines.join("\n")}\n\nTOP RISK LOCATIONS\n${top
    .map(
      (r) =>
        `${r.city}, ${r.country} — risk ${r.risk_score} (${r.risk_level}), AQI ${r.aqi}, PM2.5 ${r.pm25}, wind ${r.wind_speed} m/s`,
    )
    .join("\n")}`;
}

export async function copilotImpl(input: {
  question: string;
  cityId?: string;
  history?: Array<{ role: "user" | "assistant"; content: string }>;
}): Promise<AiEnvelope<{ text: string }>> {
  const focus = input.cityId ? riskContextFor(input.cityId) : null;
  const focusBlock = focus
    ? `\n\nFOCUS CITY: ${focus.reading.city}, ${focus.reading.country} — AQI ${focus.reading.aqi}, PM2.5 ${focus.reading.pm25}, PM10 ${focus.reading.pm10}, wind ${focus.reading.wind_speed} m/s, humidity ${focus.reading.humidity}%, risk ${focus.risk.risk_score}/100 (${focus.risk.risk_level}). Factors: ${focus.risk.factors.map((f) => `${f.label} ${f.points}/${f.max}`).join("; ")}`
    : "";

  const res = await callGemini({
    system: `You are the BRICS AirShield Climate Copilot — an analyst assistant for a cross-border air-pollution intelligence prototype covering India, Brazil, Russia, China and South Africa.
Answer only from the CONTEXT block plus general environmental-science knowledge. If asked for data not in the context, say it is not available in the prototype. Never invent live readings, government sources, satellite feeds or partnerships. Always be clear that dataset values are simulated demo data and risk scores are prototype estimates. Answer in under 180 words, using short paragraphs or bullets.`,
    prompt: `CONTEXT\n${globalContext()}${focusBlock}\n\nQUESTION: ${input.question}`,
    history: input.history,
  });

  if (res.ok) {
    return {
      data: { text: res.text.trim() },
      ai: { generated_by: "gemini", provider: res.provider, notice: GEMINI_NOTICE },
    };
  }
  return {
    data: {
      text: `The AI Copilot is temporarily unavailable, so here is the raw prototype data instead:\n\n${globalContext()}`,
    },
    ai: { generated_by: "fallback", notice: FALLBACK_NOTICE, error: res.error },
  };
}

/* ---------------------------------------------------- incident summariser */
export async function summarizeIncidentImpl(i: {
  incidentId: string;
  country: string;
  city: string;
  location: string;
  description: string;
  observedAt: string;
  riskScore: number;
  riskLevel: string;
  imageFindings?: string;
}): Promise<AiEnvelope<{ text: string }>> {
  const res = await callGemini({
    system:
      "You write concise incident briefs for environmental monitoring authorities. 3 short sections: SITUATION, ASSESSMENT, RECOMMENDED ACTION. Max 120 words total. State clearly that this is an unverified citizen report analysed by a prototype system. Never assert legal violations or name companies.",
    prompt: `Incident ${i.incidentId}
Location: ${i.location}, ${i.city}, ${i.country}
Observed: ${i.observedAt}
Reporter description: ${i.description || "(none provided)"}
AI image findings: ${i.imageFindings || "(no image analysed)"}
Prototype risk: ${i.riskScore}/100 (${i.riskLevel})`,
  });

  if (res.ok) {
    return {
      data: { text: res.text.trim() },
      ai: { generated_by: "gemini", provider: res.provider, notice: GEMINI_NOTICE },
    };
  }
  return {
    data: {
      text: `SITUATION\nUnverified citizen report ${i.incidentId} at ${i.location}, ${i.city}, ${i.country}, observed ${i.observedAt}.\n\nASSESSMENT\nPrototype risk ${i.riskScore}/100 (${levelFromScore(i.riskScore)}). ${i.imageFindings || "No image evidence analysed."}\n\nRECOMMENDED ACTION\nCross-check with local monitoring data before escalation.`,
    },
    ai: { generated_by: "fallback", notice: FALLBACK_NOTICE, error: res.error },
  };
}
