import type { ReactNode } from "react";

import { cn } from "@/lib/utils";
import type { RiskLevel } from "@/lib/risk";

const LEVEL_CLASS: Record<RiskLevel, string> = {
  LOW: "border-risk-low/40 bg-risk-low/12 text-risk-low",
  MEDIUM: "border-risk-medium/40 bg-risk-medium/12 text-risk-medium",
  HIGH: "border-risk-high/40 bg-risk-high/12 text-risk-high",
  CRITICAL: "border-risk-critical/45 bg-risk-critical/15 text-risk-critical",
};

export function RiskBadge({
  level,
  score,
  className,
}: {
  level: RiskLevel;
  score?: number;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wider",
        LEVEL_CLASS[level],
        className,
      )}
    >
      <span className="size-1.5 rounded-full bg-current" />
      {level}
      {score !== undefined ? <span className="tabular-nums opacity-80">{score}</span> : null}
    </span>
  );
}

export function Panel({
  title,
  description,
  action,
  children,
  className,
  bodyClassName,
}: {
  title?: string;
  description?: string;
  action?: ReactNode;
  children: ReactNode;
  className?: string;
  bodyClassName?: string;
}) {
  return (
    <section className={cn("panel overflow-hidden", className)}>
      {title ? (
        <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4">
          <div>
            <h2 className="text-sm font-semibold tracking-tight">{title}</h2>
            {description ? (
              <p className="mt-0.5 text-xs text-muted-foreground">{description}</p>
            ) : null}
          </div>
          {action}
        </header>
      ) : null}
      <div className={cn("p-5", bodyClassName)}>{children}</div>
    </section>
  );
}

export function StatCard({
  label,
  value,
  sub,
  icon,
  tone = "default",
}: {
  label: string;
  value: string | number;
  sub?: string;
  icon?: ReactNode;
  tone?: "default" | "warn" | "danger" | "good";
}) {
  const toneClass = {
    default: "text-foreground",
    good: "text-risk-low",
    warn: "text-risk-high",
    danger: "text-risk-critical",
  }[tone];

  return (
    <div className="panel flex items-start gap-4 p-5">
      {icon ? (
        <span className="flex size-10 shrink-0 items-center justify-center rounded-md bg-secondary text-primary">
          {icon}
        </span>
      ) : null}
      <div className="min-w-0">
        <p className="text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
          {label}
        </p>
        <p className={cn("stat-value mt-1 text-3xl font-semibold", toneClass)}>{value}</p>
        {sub ? <p className="mt-1 truncate text-xs text-muted-foreground">{sub}</p> : null}
      </div>
    </div>
  );
}

export function AiNotice({
  generatedBy,
  provider,
  error,
}: {
  generatedBy: "gemini" | "fallback";
  provider?: string | undefined;
  error?: string | undefined;
}) {
  const gemini = generatedBy === "gemini";
  return (
    <p
      className={cn(
        "mt-4 rounded-md border px-3 py-2 text-[11px] leading-relaxed",
        gemini
          ? "border-primary/30 bg-primary/8 text-primary"
          : "border-risk-medium/35 bg-risk-medium/10 text-risk-medium",
      )}
    >
      {gemini ? (
        <>
          Generated by <strong>Google Gemini</strong>
          {provider === "lovable-gemini-gateway" ? " (via AI gateway)" : " (AI Studio API)"}. AI
          assistance only — not an official environmental diagnosis.
        </>
      ) : (
        <>
          <strong>DEMO FALLBACK — not AI generated.</strong> Google Gemini was unavailable
          {error ? ` (${error})` : ""}, so this output came from the local rule engine.
        </>
      )}
    </p>
  );
}

export function Empty({ children }: { children: ReactNode }) {
  return (
    <div className="rounded-md border border-dashed border-border px-5 py-10 text-center text-sm text-muted-foreground">
      {children}
    </div>
  );
}
